### ISSUE TITLE
Location layer doesn't display current location immediately.

### ISSUE THREAD

**Issue by hangduykhiem** [mapbox/mapbox-plugins-android#424]
First off, thanks for the great work with the SDK and plugins. 

Currently I'm running into this one problem trying to get user location to work. Basically, the Location Layer plugin doesn't immediately display the current location of user. 
Sometimes you can force the location display by going out of the application and going in again, and sometimes you can just wait a bit for it to appear on the screen.

The behavior can be seen in this gif here.

![ezgif-1-e331f3787d](https://user-images.githubusercontent.com/8597129/38725060-c523d8de-3f0e-11e8-8585-805835075d5d.gif)

Here is my setup function:

```java
    private void setupMapView() {
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(final MapboxMap mapboxMap) {
                if (PermissionsManager.areLocationPermissionsGranted(MainActivity.this)) {
                    locationEngine = new LocationEngineProvider(MainActivity.this).obtainLocationEngineBy(LocationEngine.Type.ANDROID);
                    locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
                    locationEngine.addLocationEngineListener(new LocationEngineListener() {
                        @Override
                        public void onConnected() {
                            locationEngine.requestLocationUpdates();
                        }

                        @Override
                        public void onLocationChanged(Location location) {
                            setCameraPosition(mapboxMap, location);
                            locationEngine.removeLocationEngineListener(this);
                        }
                    });
                    locationEngine.activate();
                    locationPlugin = new LocationLayerPlugin(mapView, mapboxMap, locationEngine);
                }

                mapboxMap.getUiSettings().setCompassEnabled(false);
                mapboxMap.getUiSettings().setRotateGesturesEnabled(false);
                mapboxMap.getUiSettings().setTiltGesturesEnabled(false);
            }
        });
    }


    private void setCameraPosition(MapboxMap map, Location location) {
        map.animateCamera(CameraUpdateFactory.newLatLngZoom(
                new LatLng(location.getLatitude(), location.getLongitude()), 13));
    }

    @Override
    @SuppressWarnings({"MissingPermission"})
    protected void onStart() {
        super.onStart();
        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
        }
        if (locationPlugin != null) {
            locationPlugin.onStart();
        }
        mapView.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (locationEngine != null) {
            locationEngine.removeLocationUpdates();
        }
        if (locationPlugin != null) {
            locationPlugin.onStop();
        }
        mapView.onStop();
    }
```

**Comment by LukasPaczos** [comment]
Thanks for reaching out @hangduykhiem. We are including tons of improvements to the `LocationLayerPlugin` that will be available with `0.5.0` which comes out next week and this issue should be resolved.

In the meantime, could you retest with `0.5.0-beta.2` and let us know whether it works for you?

**Comment by hangduykhiem** [comment]
I tried this with both 0.5.0-beta.2 and 0.4.0, on both sdk 6.0.0-beta6 and 5.5.0. The behavior seem to appear on both of them.

**Comment by danesfeder** [comment]
Hey @hangduykhiem, #420 didn't land in time for `beta.2` - you can test with the `0.5.0-SNAPSHOT` which should reflect latest `master`.  I will retest again on our side to confirm this is no longer an issue with this fix.

**Comment by Guardiola31337** [comment]
Sad news here 😥

![first-location-issue](https://user-images.githubusercontent.com/1668582/38754799-7dcbb9ac-3f63-11e8-9acc-0befd815dda7.gif)


Retested including #420 and this is still an issue. It should be something else.

We'll keep digging 🕵️ and report back here. Thanks for the report @hangduykhiem 🙏

cc @danesfeder @LukasPaczos

**Comment by langsmith** [comment]
@danesfeder, I'm seeing the same thing in the demo app

cc @Guardiola31337 who's reported this internally too.

**Comment by LukasPaczos** [comment]
Landed with https://github.com/mapbox/mapbox-plugins-android/pull/431.

**Comment by Guardiola31337** [comment]
Confirming that OP is fixed in [`0.5.0`](https://github.com/mapbox/mapbox-plugins-android/releases/tag/v0.5.0-location-layer) 🎉 

![initial_position_working_0_5_0](https://user-images.githubusercontent.com/1668582/39044720-4d9ecfe8-4491-11e8-8a57-ad2ea2a11c07.gif)

cc @danesfeder @LukasPaczos @hangduykhiem
